=== safa2-code/XML-and-Json/dtd/mobiles.dtd
<!ELEMENT mobiles (mobile+)>
<!ELEMENT mobile (company,model,price,accessories)>
<!ELEMENT company (#PCDATA)>
<!ELEMENT  model (#PCDATA)>
<!ELEMENT price (#PCDATA)>
<!ELEMENT accessories (#PCDATA)>
<!ATTLIST model type CDATA  "camera">
<!ENTITY hp "head phone">
<!ENTITY ch "charger">
<!ENTITY sk "starter kit">

=== safa2-code/XML-and-Json/xml/mobiles_external_dtd.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE mobiles SYSTEM "../dtd/mobiles.dtd" >

<mobiles>
    <mobile>
        <company>Galaxy</company>
        <model type="camera">S26</model>
        <price>150,000</price>
        <accessories>&sk;,&ch;</accessories> 
    </mobile>   
    <mobile>
        <company>Oneplus</company>
        <model type="camera">Oneplus</model>
        <price>45,000</price>
        <accessories>&sk; &ch;</accessories> 
    </mobile>   
    <mobile>
        <company>Nokia</company>
        <model type="camera">X30</model>
        <price>110,000</price>
        <accessories>&sk;, &hp;, &ch;</accessories> 
    </mobile>   
</mobiles>
